from __future__ import annotations

from app.core.topics.contracts import SkillDefinition

GROUP_LABELS = {
    "foundation": "Positional systems",
    "binary_decimal": "Binary ↔ Decimal",
    "octal": "Binary ↔ Octal",
    "hexadecimal": "Binary ↔ Hexadecimal",
    "cross_base": "Four-system conversion",
    "data_units": "Bits and bytes",
    "rgb": "RGB colours",
    "characters": "Character codes",
    "metaconcept": "Representation and meaning",
}


_SPECS: tuple[tuple[str, str, str, tuple[str, ...], int, tuple[str, ...]], ...] = (
    (
        "foundation:representation_value",
        "foundation",
        "Representation versus value",
        (),
        1,
        ("concept", "diagnostic"),
    ),
    ("foundation:positional_value", "foundation", "Positional value", (), 1, ("concept",)),
    ("foundation:powers", "foundation", "Powers of the base", (), 1, ("concept",)),
    ("foundation:valid_digits", "foundation", "Valid digits", (), 1, ("concept",)),
    ("foundation:meaning_ten", "foundation", "Meaning of 10", (), 1, ("concept",)),
    (
        "binary_decimal:bin_to_dec",
        "binary_decimal",
        "Binary to decimal",
        ("foundation:positional_value",),
        1,
        ("conversion", "diagnostic"),
    ),
    (
        "binary_decimal:dec_to_bin",
        "binary_decimal",
        "Decimal to binary",
        ("foundation:powers",),
        1,
        ("conversion", "diagnostic"),
    ),
    (
        "binary_decimal:binary_addition",
        "binary_decimal",
        "Binary addition",
        ("foundation:positional_value",),
        2,
        ("concept", "diagnostic"),
    ),
    ("binary_decimal:bit_length", "binary_decimal", "Bit-length recognition", (), 2, ("concept",)),
    (
        "octal:three_bit_mapping",
        "octal",
        "Three-bit octal mapping",
        ("binary_decimal:bin_to_dec",),
        2,
        ("concept",),
    ),
    (
        "octal:bin_to_oct",
        "octal",
        "Binary to octal",
        ("octal:three_bit_mapping",),
        2,
        ("conversion",),
    ),
    (
        "octal:oct_to_bin",
        "octal",
        "Octal to binary",
        ("octal:three_bit_mapping",),
        2,
        ("conversion",),
    ),
    (
        "octal:dec_to_oct",
        "octal",
        "Decimal to octal",
        ("foundation:powers",),
        3,
        ("conversion",),
    ),
    (
        "octal:oct_to_dec",
        "octal",
        "Octal to decimal",
        ("foundation:positional_value",),
        3,
        ("conversion",),
    ),
    ("hexadecimal:digits", "hexadecimal", "Hexadecimal digit values", (), 1, ("concept",)),
    (
        "hexadecimal:four_bit_mapping",
        "hexadecimal",
        "Four-bit hexadecimal mapping",
        ("hexadecimal:digits", "binary_decimal:bin_to_dec"),
        2,
        ("concept",),
    ),
    (
        "hexadecimal:bin_to_hex",
        "hexadecimal",
        "Binary to hexadecimal",
        ("hexadecimal:four_bit_mapping",),
        2,
        ("conversion",),
    ),
    (
        "hexadecimal:hex_to_bin",
        "hexadecimal",
        "Hexadecimal to binary",
        ("hexadecimal:four_bit_mapping",),
        2,
        ("conversion",),
    ),
    (
        "hexadecimal:dec_to_hex",
        "hexadecimal",
        "Decimal to hexadecimal",
        ("hexadecimal:digits", "foundation:powers"),
        3,
        ("conversion",),
    ),
    (
        "hexadecimal:hex_to_dec",
        "hexadecimal",
        "Hexadecimal to decimal",
        ("hexadecimal:digits", "foundation:positional_value"),
        3,
        ("conversion",),
    ),
    (
        "cross_base:oct_to_hex",
        "cross_base",
        "Octal to hexadecimal",
        ("octal:oct_to_bin", "hexadecimal:bin_to_hex"),
        4,
        ("conversion", "transfer"),
    ),
    (
        "cross_base:hex_to_oct",
        "cross_base",
        "Hexadecimal to octal",
        ("hexadecimal:hex_to_bin", "octal:bin_to_oct"),
        4,
        ("conversion", "transfer"),
    ),
    ("cross_base:equivalent", "cross_base", "Equivalent representations", (), 3, ("concept",)),
    ("cross_base:compare", "cross_base", "Compare values across bases", (), 3, ("concept",)),
    (
        "cross_base:efficient_route",
        "cross_base",
        "Choose an efficient conversion route",
        ("octal:bin_to_oct", "hexadecimal:bin_to_hex"),
        4,
        ("concept", "transfer"),
    ),
    ("data_units:bit", "data_units", "Bit", (), 1, ("concept",)),
    ("data_units:nibble", "data_units", "Nibble", ("data_units:bit",), 2, ("concept",)),
    ("data_units:byte", "data_units", "Byte", ("data_units:bit",), 2, ("concept",)),
    (
        "data_units:patterns",
        "data_units",
        "Number of bit patterns",
        ("data_units:bit",),
        2,
        ("concept", "application"),
    ),
    (
        "data_units:byte_range",
        "data_units",
        "Unsigned byte range",
        ("data_units:patterns", "data_units:byte"),
        2,
        ("concept", "application"),
    ),
    (
        "data_units:leading_zeroes",
        "data_units",
        "Leading zeroes and fixed width",
        ("data_units:byte",),
        3,
        ("concept",),
    ),
    (
        "rgb:channels",
        "rgb",
        "RGB channel interpretation",
        ("data_units:byte",),
        3,
        ("application",),
    ),
    (
        "rgb:dec_to_hex",
        "rgb",
        "Decimal channel to hexadecimal",
        ("hexadecimal:dec_to_hex", "data_units:byte_range"),
        4,
        ("conversion", "application"),
    ),
    (
        "rgb:hex_to_dec",
        "rgb",
        "Hexadecimal channel to decimal",
        ("hexadecimal:hex_to_dec", "data_units:byte_range"),
        4,
        ("conversion", "application"),
    ),
    (
        "rgb:complete_code",
        "rgb",
        "Complete hexadecimal colour code",
        ("rgb:dec_to_hex",),
        4,
        ("application",),
    ),
    ("rgb:visual", "rgb", "Visual colour reasoning", ("rgb:channels",), 4, ("application",)),
    (
        "rgb:binary",
        "rgb",
        "Binary RGB representation",
        ("rgb:complete_code", "hexadecimal:hex_to_bin"),
        5,
        ("application", "transfer"),
    ),
    (
        "characters:assigned_code",
        "characters",
        "Characters as assigned codes",
        ("data_units:byte",),
        3,
        ("concept",),
    ),
    (
        "characters:decimal",
        "characters",
        "ASCII decimal code",
        ("characters:assigned_code",),
        3,
        ("application",),
    ),
    (
        "characters:hex",
        "characters",
        "ASCII hexadecimal code",
        ("characters:assigned_code",),
        4,
        ("application",),
    ),
    (
        "characters:binary",
        "characters",
        "ASCII binary byte",
        ("characters:assigned_code",),
        4,
        ("application",),
    ),
    (
        "characters:code_to_char",
        "characters",
        "Code to character",
        ("characters:assigned_code",),
        4,
        ("application",),
    ),
    (
        "characters:decode",
        "characters",
        "Short ASCII decoding",
        ("characters:code_to_char",),
        5,
        ("application", "transfer"),
    ),
    (
        "characters:numeric_vs_char",
        "characters",
        "Numeric value versus character",
        ("characters:assigned_code",),
        4,
        ("concept", "transfer"),
    ),
    (
        "metaconcept:bits_interpretation",
        "metaconcept",
        "Bits require interpretation",
        ("data_units:byte", "characters:assigned_code"),
        5,
        ("concept", "transfer"),
    ),
    (
        "metaconcept:hex_compact",
        "metaconcept",
        "Hexadecimal as compact bit notation",
        ("hexadecimal:four_bit_mapping",),
        3,
        ("concept",),
    ),
    (
        "metaconcept:same_value",
        "metaconcept",
        "One value, several representations",
        ("cross_base:equivalent",),
        4,
        ("concept", "transfer"),
    ),
    (
        "metaconcept:same_bits",
        "metaconcept",
        "One bit pattern, several meanings",
        ("metaconcept:bits_interpretation",),
        5,
        ("concept", "transfer"),
    ),
)


LABELS = {key: label for key, _, label, _, _, _ in _SPECS}


def skill_catalogue() -> tuple[SkillDefinition, ...]:
    return tuple(
        SkillDefinition(
            skill_key=key,
            group_key=group,
            title_key=f"skill.{key.replace(':', '.')}",
            description_key=f"skill.{key.replace(':', '.')}.description",
            prerequisites=prerequisites,
            difficulty=difficulty,
            tags=tags,
        )
        for key, group, _, prerequisites, difficulty, tags in _SPECS
    )


def skill_label(skill_key: str) -> str:
    try:
        return LABELS[skill_key]
    except KeyError as exc:
        raise ValueError(f"unknown numeral-systems skill: {skill_key}") from exc
